<?php
$e=static fn(mixed $v):string=>htmlspecialchars((string)$v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');
?>
<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#172033"><link rel="manifest" href="/manifest.webmanifest"><title>Releasecenter – MeldeVerkehr</title>
<style>body{font-family:system-ui,sans-serif;background:#f4f6f9;color:#172033;margin:0}main{max-width:1100px;margin:32px auto;padding:20px}.card{background:#fff;border:1px solid #dce3eb;border-radius:14px;padding:20px;margin-bottom:16px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:14px}.ok{color:#24683b;font-weight:800}.bad{color:#8e1f1f;font-weight:800}.warn{color:#8a5a0a;font-weight:800}.muted{color:#657389}.message,.error{padding:12px;border-radius:9px;margin-bottom:14px}.message{border:1px solid #8fb799}.error{border:1px solid #c99}button,.button{display:inline-block;padding:10px 14px;border:0;border-radius:9px;background:#172033;color:#fff;text-decoration:none;font-weight:700}input{padding:9px;border:1px solid #bac5d1;border-radius:8px}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:9px;border-bottom:1px solid #edf0f4}.danger{background:#8e1f1f}</style></head><body><main>
<p><a href="/admin">← Administration</a></p><h1>Releasecenter</h1>
<?php if($message):?><div class="message"><?= $e($message) ?></div><?php endif;?><?php if($error):?><div class="error"><?= $e($error) ?></div><?php endif;?>
<section class="card"><h2>Release-Status</h2><div class="grid"><div><strong>Code-Version</strong><br><?= $e($currentVersion) ?></div><div><strong>Letzte Runtime-Version</strong><br><?= $e($lastVersion?:'noch nicht gesetzt') ?></div><div><strong>Readiness</strong><br><span class="<?= $readiness['ready']?'ok':'bad' ?>"><?= $readiness['ready']?'BEREIT':'NICHT BEREIT' ?></span></div><div><strong>Maintenance</strong><br><span class="<?= $maintenance['active']?'warn':'ok' ?>"><?= $maintenance['active']?'AKTIV':'AUS' ?></span></div></div></section>
<section class="card"><h2>Readiness-Checks</h2><table><thead><tr><th>Check</th><th>Status</th><th>Hinweis</th></tr></thead><tbody><?php foreach($readiness['checks'] as $check):?><tr><td><?= $e($check['key']) ?></td><td class="<?= $check['ok']?'ok':($check['blocking']?'bad':'warn') ?>"><?= $check['ok']?'OK':($check['blocking']?'BLOCKIERT':'WARNUNG') ?></td><td><?= $e($check['message']) ?></td></tr><?php endforeach;?></tbody></table></section>
<section class="card"><h2>Backup</h2><p class="muted">Backups werden außerhalb des Webroots abgelegt. Datenbank und Runtime-Dateien werden verschlüsselt und gehasht.</p><form method="post" action="/admin/system/update/backup"><input type="hidden" name="_csrf" value="<?= $e($csrf) ?>"><label><input type="checkbox" name="database_only" value="1"> Nur Datenbank</label> <button type="submit">Backup erstellen</button></form><h3>Letzte Backups</h3><table><thead><tr><th>ID</th><th>Typ</th><th>Status</th><th>DB</th><th>Runtime</th><th>Aktion</th></tr></thead><tbody><?php foreach($backups as $b):?><tr><td><code><?= $e($b['id']) ?></code></td><td><?= $e($b['backup_type']) ?></td><td><?= $e($b['status']) ?></td><td><?= $e(round(((int)$b['database_bytes'])/1024,1)) ?> KB</td><td><?= $e($b['runtime_files']) ?> Dateien</td><td><?php if($b['status']==='READY'):?><form method="post" action="/admin/system/update/backups/<?= rawurlencode($b['id']) ?>/verify"><input type="hidden" name="_csrf" value="<?= $e($csrf) ?>"><button type="submit">Verifizieren</button></form><?php endif;?></td></tr><?php endforeach;?></tbody></table></section>
<section class="card"><h2>Update ausführen</h2><p class="muted">Vor dem Lauf müssen die neuen Dateien bereits per Git/Upload auf dem Server liegen. Der Update-Lauf aktiviert Maintenance, erstellt und verifiziert ein vollständiges Backup, führt Migrationen aus und deaktiviert Maintenance nur bei Erfolg.</p><form method="post" action="/admin/system/update/run"><input type="hidden" name="_csrf" value="<?= $e($csrf) ?>"><label>Ausgangsversion <input name="from_version" value="<?= $e($lastVersion) ?>" placeholder="z. B. 0.11.0-dev" required></label> <button type="submit">Update auf <?= $e($currentVersion) ?> starten</button></form><?php if($maintenance['active']):?><form method="post" action="/admin/system/update/maintenance-off" style="margin-top:12px"><input type="hidden" name="_csrf" value="<?= $e($csrf) ?>"><button class="danger" type="submit">Maintenance manuell deaktivieren</button></form><?php endif;?></section>
<section class="card"><h2>Update-Historie</h2><table><thead><tr><th>Von</th><th>Nach</th><th>Status</th><th>Backup</th><th>Start</th></tr></thead><tbody><?php foreach($updates as $u):?><tr><td><?= $e($u['from_version']) ?></td><td><?= $e($u['to_version']) ?></td><td><?= $e($u['status']) ?></td><td><?= $e($u['backup_id']??'–') ?></td><td><?= $e($u['started_at']) ?></td></tr><?php endforeach;?></tbody></table></section>
<p class="muted">Destruktiver Restore bleibt absichtlich CLI-only: <code>php maintenance.php restore &lt;BACKUP-ID&gt; --confirm</code></p>
</main><script src="/assets/app.js" defer></script></body></html>