<?php $e=static fn(mixed $v):string=>htmlspecialchars((string)$v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8'); ?>
<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= $e($area['name']) ?> – MeldeVerkehr</title>
<style>body{font-family:system-ui,sans-serif;background:#f5f7fa;color:#172033;margin:0}main{max-width:1000px;margin:28px auto;padding:20px}.card{background:#fff;border:1px solid #dfe5ec;border-radius:15px;padding:22px;margin-bottom:14px}.message,.error{padding:12px;border-radius:9px;margin-bottom:12px}.message{border:1px solid #8fb799}.error{border:1px solid #c99}table{width:100%;border-collapse:collapse}td,th{padding:8px;border-bottom:1px solid #e5e9ee;text-align:left}button{padding:10px 14px;border:0;border-radius:9px;background:#172033;color:white;font-weight:700}.muted{color:#66758a}input{padding:9px;border:1px solid #bac5d1;border-radius:8px}</style></head><body><main>
<p><a href="/problem-areas">← Problemstellen</a></p><h1><?= $e($area['name']) ?></h1><p><?= $e(trim(($area['street']??'').' '.($area['city']??''))) ?> · Radius <?= $e($area['radius_m']) ?> m</p>
<?php if($message):?><div class="message"><?= $e($message) ?></div><?php endif;?><?php if($error):?><div class="error"><?= $e($error) ?></div><?php endif;?>
<section class="card"><h2>Zuordnung aktualisieren</h2><p class="muted">Es werden ausschließlich deine eigenen Vorgänge mit GPS-Koordinaten berücksichtigt.</p><form method="post" action="/problem-areas/<?= rawurlencode($area['id']) ?>/sync"><input type="hidden" name="_csrf" value="<?= $e($csrf) ?>"><button type="submit">Eigene Vorgänge neu zuordnen</button></form></section>
<section class="card"><h2>Aktuelle Kennzahlen</h2><p><strong><?= $e($area['metrics']['case_count']) ?></strong> zugeordnete Vorgänge</p><?php foreach($area['metrics']['offense_category_counts'] as $r):?><p><?= $e($r['label']) ?>: <?= $e($r['count']) ?></p><?php endforeach;?></section>
<section class="card"><h2>Zugeordnete Vorgänge</h2><table><tr><th>Vorgang</th><th>Zeit</th><th>Tatbestand</th><th>Distanz</th></tr><?php foreach($area['cases'] as $c):?><tr><td><a href="/cases/<?= rawurlencode($c['id']) ?>"><?= $e($c['public_number']) ?></a></td><td><?= $e($c['observed_from']??'') ?></td><td><?= $e($c['offense_title']??'–') ?></td><td><?= $e($c['distance_m']) ?> m</td></tr><?php endforeach;?></table></section>
<section class="card"><h2>Anonymisierten kommunalen Problembericht erzeugen</h2><p class="muted">Der Report enthält nur Aggregationen. Keine Kennzeichen, keine Halterdaten, keine Vorgangs-IDs und standardmäßig keine Fotos.</p><form method="post" action="/problem-areas/<?= rawurlencode($area['id']) ?>/reports"><input type="hidden" name="_csrf" value="<?= $e($csrf) ?>"><label>Von <input type="date" name="from" required></label> <label>Bis <input type="date" name="to" required></label><br><button type="submit">Bericht erzeugen</button></form></section>
</main></body></html>