<?php
$e=static fn(mixed $v):string=>htmlspecialchars((string)$v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');
$m=$detail['manifest']; $snap=$m['witness_report']['snapshot']??[]; $narrative=$snap['narrative']['text']??'';
?>
<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= $e($m['case']['public_number']??'Behördenvorgang') ?> – MeldeVerkehr</title>
<style>body{font-family:system-ui,sans-serif;background:#f5f7fa;color:#172033;margin:0}main{max-width:1000px;margin:28px auto;padding:20px}.card{background:#fff;border:1px solid #dfe5ec;border-radius:15px;padding:20px;margin-bottom:14px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px}textarea,input,select{width:100%;box-sizing:border-box;padding:9px;border:1px solid #bac5d1;border-radius:8px}button,.button{display:inline-block;padding:9px 13px;border:0;border-radius:9px;background:#172033;color:#fff;text-decoration:none;font-weight:700}.message,.error{padding:10px;border-radius:8px}.message{border:1px solid #8fb799}.error{border:1px solid #c99}.muted{color:#66758a}.hash{font-family:ui-monospace,monospace;font-size:.78rem;word-break:break-all}.inquiry{border-top:1px solid #e5e9ee;padding:12px 0}</style></head><body><main>
<p><a href="/authority?authority=<?= rawurlencode($detail['authority']['id']) ?>">← Behördenportal</a></p>
<h1><?= $e($m['case']['public_number']??'Behördenvorgang') ?></h1>
<?php if($message):?><div class="message"><?= $e($message) ?></div><?php endif;?><?php if($error):?><div class="error"><?= $e($error) ?></div><?php endif;?>
<section class="card"><h2>Übermittelter Snapshot</h2><p><strong>Behörde:</strong> <?= $e($detail['authority']['name']) ?></p><p><strong>Übermittelt:</strong> <?= $e($detail['dispatch']['sent_at']) ?></p><p><strong>Meldende Person:</strong> <?= $e(trim(($m['reporter']['first_name']??'').' '.($m['reporter']['last_name']??''))) ?> · <?= $e($m['reporter']['email']??'') ?></p><p><strong>Sachverhalt:</strong></p><p><?= nl2br($e($narrative)) ?></p><p><strong>Beweisanlagen:</strong> <?= $e(count($m['evidence_package']['items']??[])) ?></p><p class="hash">Dispatch-Paket SHA‑256: <?= $e($detail['dispatch']['package_sha256']) ?></p></section>
<?php if(($scope['scope_role']??'')==='AUTHORITY_ADMIN'):?><section class="card"><h2>Geschützter Halterbereich</h2><p class="muted">Halterdaten werden getrennt verschlüsselt gespeichert und sind nicht Bestandteil der Bürgerakte oder normaler Exporte.</p><a class="button" href="/authority/cases/<?= rawurlencode($m['case']['id']) ?>/holder">Halterdaten öffnen</a></section><?php endif;?>
<section class="card"><h2>Strukturierte Anfrage</h2><form method="post" action="/authority/cases/<?= rawurlencode($m['case']['id']) ?>/inquiries"><input type="hidden" name="_csrf" value="<?= $e($csrf) ?>"><div class="grid"><div><label>Typ</label><select name="inquiry_type"><option value="TIME">Zeit</option><option value="PHOTO">Foto/Nachweis</option><option value="LOCATION">Ort</option><option value="WITNESS">Zeuge</option><option value="OTHER">Sonstiges</option></select></div><div><label>Frist optional</label><input type="datetime-local" name="due_at"></div></div><label>Betreff</label><input name="subject" maxlength="255" required><label>Text</label><textarea name="body" rows="5" maxlength="10000" required></textarea><button type="submit">Anfrage erstellen</button></form></section>
<section class="card"><h2>Bisherige Anfragen</h2><?php foreach($detail['inquiries'] as $inq):?><div class="inquiry"><strong><?= $e($inq['inquiry_type']) ?> · <?= $e($inq['subject']) ?></strong><p><?= nl2br($e($inq['body'])) ?></p><small class="muted"><?= $e($inq['status']) ?> · <?= $e($inq['created_at']) ?><?php if($inq['due_at']):?> · Frist <?= $e($inq['due_at']) ?><?php endif;?></small></div><?php endforeach;?><?php if(!$detail['inquiries']):?><p class="muted">Noch keine Portal-Anfragen.</p><?php endif;?></section>
</main><script src="/assets/app.js" defer></script></body></html>